"""The v2 (band-limited) synthetic generator.

Three things are pinned here, and each of them is a thing that has already gone
wrong once:

* **determinism**, by hash.  Every quality number in this project is a number
  about some material; if the material moves, the number means nothing, and a
  corpus hash in `corpus/MANIFEST.json` is only as good as the generator's
  promise to reproduce it.
* **the ceiling**, because the point of v2 is that band-limited ground truth
  can be predicted by a warp and v1's could not (docs/WARP-AUDIT.md section 4).
  A regression that quietly reintroduces aliasing would not fail any other test
  in this suite -- it would just make the codec look bad, which is
  indistinguishable from the codec being bad.
* **`--legacy`**, against a hash from before the change, because the whole
  argument for regenerating the corpus is that the old numbers stay
  reproducible.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys

import numpy as np
import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

from capture import gen_synthetic, synth  # noqa: E402
from nxq import yuv  # noqa: E402

#: A 3-frame 64x64 mono clip, the smallest thing that exercises the whole v2
#: path (panorama, prefilter, 4x4 supersample, ceiling, sidecar).
PIN_ARGS = ["--frames", "3", "--eye-width", "64", "--eye-height", "64",
            "--motion", "mixed", "--layout", "mono", "--pix", "yuv444p",
            "--seed", "1", "--quiet"]
PIN_V2_SHA = "1771b24d93730330481484dab16f7d1b35d363ca4b1dc82024362afec07d038f"
PIN_V1_SHA = "3e8858fed59e60c145376a09b5bb2aa5cd2333cee66b8282057fe27e35f3b7a1"

#: From `corpus/MANIFEST.json` *before* the v2 change: `panel-static-256`'s
#: 4:4:4 data, generated by version 1 of this script.  `--legacy` has to
#: reproduce it byte for byte or every number ever published on that entry
#: becomes unreproducible.
CORPUS_PANEL_V1_SHA = "3702cc6b50bbde32e4546f68233b675dd59d6b9536504e6ce519cb27a8d06926"


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def gen(out: str, name: str, extra: list[str]) -> str:
    assert gen_synthetic.main(["--out", out, "--name", name] + PIN_ARGS + extra) == 0
    return os.path.join(out, f"{name}.yuv444p.yuv")


class TestDeterminism:
    def test_v2_hash_is_pinned(self, tmp_path):
        assert sha256(gen(str(tmp_path), "a", [])) == PIN_V2_SHA

    def test_v2_repeats_itself(self, tmp_path):
        a = sha256(gen(str(tmp_path), "a", []))
        b = sha256(gen(str(tmp_path), "b", []))
        assert a == b

    def test_supersampling_changes_the_bytes(self, tmp_path):
        """Guard against --supersample being read and ignored."""
        a = sha256(gen(str(tmp_path), "a", []))
        b = sha256(gen(str(tmp_path), "b", ["--supersample", "2"]))
        assert a != b


class TestLegacy:
    def test_legacy_hash_is_pinned(self, tmp_path):
        assert sha256(gen(str(tmp_path), "a", ["--legacy"])) == PIN_V1_SHA

    def test_legacy_differs_from_v2(self, tmp_path):
        assert sha256(gen(str(tmp_path), "a", ["--legacy"])) != PIN_V2_SHA

    def test_legacy_reproduces_the_published_corpus_bytes(self, tmp_path):
        """The v1 hash that was in corpus/MANIFEST.json before this change."""
        assert gen_synthetic.main([
            "--out", str(tmp_path), "--name", "panel-static-256",
            "--frames", "6", "--eye-width", "256", "--eye-height", "256",
            "--motion", "static", "--layout", "sbs", "--pix", "yuv444p",
            "--fps", "90.0", "--seed", "7", "--objects", "0", "--no-hud",
            "--legacy", "--quiet"]) == 0
        got = sha256(os.path.join(str(tmp_path), "panel-static-256.yuv444p.yuv"))
        assert got == CORPUS_PANEL_V1_SHA

    def test_legacy_pose_log_carries_no_v2_blocks(self, tmp_path):
        """A legacy pose log must be byte-identical to what v1 wrote."""
        gen(str(tmp_path), "a", ["--legacy", "--ceiling"])
        doc = json.load(open(os.path.join(str(tmp_path), "a.poses.json")))
        assert doc["version"] == 2  # the sidecar schema, not the generator
        assert "render" not in doc
        assert "ideal_warp_ceiling" not in doc


@pytest.fixture(scope="module")
def doc(tmp_path_factory):
    """One v2 pose log, shared: generating it is the slow part."""
    d = str(tmp_path_factory.mktemp("sidecar"))
    gen(d, "a", [])
    return json.load(open(os.path.join(d, "a.poses.json")))


class TestSidecar:
    def test_records_how_it_band_limited(self, doc):
        r = doc["render"]
        assert r["generator"] == 2 and r["band_limited"] is True
        assert r["supersample"] >= 4
        assert r["panorama_oversampling"] > 4.0

    def test_records_the_ceiling(self, doc):
        c = doc["ideal_warp_ceiling"]
        assert c["frames"] == 2
        assert len(c["per_frame"]) == 2
        for k in ("mean_db", "min_db", "max_db", "first_db"):
            assert np.isfinite(c["full"][k]) and np.isfinite(c["centre"][k])

    def test_the_encoder_can_still_parse_it(self, doc):
        """nxv-enc scans for the first `"id"` and the first `"fov_deg"`.

        Both v2 blocks are keyed so that neither can be the one it finds, and
        both sit after `convention` in the file.  If that stops being true the
        encoder silently derives its homography from the wrong numbers, which
        is exactly the class of defect docs/WARP-AUDIT.md section 5 found.
        """
        keys = list(doc)
        assert keys.index("convention") < keys.index("render")
        assert doc["convention"]["id"] == "nxv-openxr-1"
        assert doc["fov_deg"] == {"h": 95.0, "v": 95.0}
        blob = json.dumps({k: doc[k] for k in ("render", "ideal_warp_ceiling")})
        assert '"id"' not in blob
        assert "fov_deg" not in blob
        assert "orientation_xyzw" not in blob


def _pure_rotation_ceiling(eye: int, degrees: float, band_limited: bool) -> tuple[float, float]:
    """Ideal-warp PSNR over one pure-rotation pair, full frame and centre crop."""
    cam = synth.Camera(eye, eye)
    ppd = synth.eye_ppd(cam)
    ss = 4 if band_limited else 1
    pano_w = max(2048, eye * (16 if band_limited else 8))
    pano = synth.make_panorama(
        pano_w, pano_w // 2, seed=1,
        feature_scale=(synth.equirect_ppd(pano_w) / ppd) if band_limited else 1.0)
    if band_limited:
        pano = synth.prefilter_equirect(pano, ppd * ss)

    def pose(i, yaw):
        return {"frame": i, "time_s": 0.0, "position_xyz": [0.0, 0.0, 0.0],
                "orientation_xyzw": [0.0, 0.0, 0.0, 1.0], "yaw_deg": yaw,
                "pitch_deg": yaw * 0.3, "roll_deg": yaw * 0.15,
                "angular_velocity_deg_s": 0.0}

    ps = [pose(0, 0.0), pose(1, degrees)]
    ys = []
    for p in ps:
        rgb = (synth.render_view_ss(pano, cam, p, None, 0, ss=ss, hud=False) if band_limited
               else synth.render_view(pano, cam, p, None, 0, hud=False))
        ys.append(yuv.rgb_to_yuv444(rgb).y)
    pred = synth.ideal_warp(ys[0], ps[0], ps[1], cam)
    return (synth.psnr(pred, ys[1]),
            synth.psnr(synth.centre_crop(pred), synth.centre_crop(ys[1])))


class TestCeiling:
    def test_band_limited_pure_rotation_clears_35_db_at_10_degrees(self):
        """The measurement the whole v2 change exists to make possible.

        A pure rotation of a static world is the one thing a rotation-only warp
        predicts exactly, so on properly band-limited ground truth the ideal
        warp has to be *good*.  On v1 material it scored 31.4 dB at 10 degrees
        and the 8 dB in docs/WARP-AUDIT.md was blamed on the codec for a while.
        """
        _, centre = _pure_rotation_ceiling(128, 10.0, band_limited=True)
        assert centre > 35.0, f"band-limited 10 deg ceiling is only {centre:.2f} dB"

    def test_band_limiting_is_worth_several_db_over_v1(self):
        _, v2 = _pure_rotation_ceiling(128, 10.0, band_limited=True)
        _, v1 = _pure_rotation_ceiling(128, 10.0, band_limited=False)
        assert v2 - v1 > 5.0, f"v2 {v2:.2f} dB is not clear of v1 {v1:.2f} dB"

    def test_identity_pose_is_a_bit_exact_copy(self):
        """The sanity check: no rotation must mean no loss, or the ceiling is
        measuring a coordinate error rather than the material."""
        full, centre = _pure_rotation_ceiling(64, 0.0, band_limited=True)
        assert full > 90.0 and centre > 90.0

    def test_the_warp_is_worth_far_more_than_no_warp(self):
        """`ideal_warp` is written from this module's own projection maths, so
        it could in principle agree with itself while disagreeing with the
        renderer.  Compare it against applying no warp at all -- the floor
        docs/WARP-AUDIT.md section 3 measures every broken convention against.
        A wrongly oriented warp scores about what the floor scores; a correct
        one is far above it."""
        cam = synth.Camera(128, 128)
        ppd = synth.eye_ppd(cam)
        pano = synth.prefilter_equirect(
            synth.make_panorama(2048, 1024, seed=1,
                                feature_scale=synth.equirect_ppd(2048) / ppd), ppd * 4)

        def pose(i, yaw):
            return {"frame": i, "time_s": 0.0, "position_xyz": [0.0, 0.0, 0.0],
                    "orientation_xyzw": [0.0, 0.0, 0.0, 1.0], "yaw_deg": yaw,
                    "pitch_deg": yaw * 0.3, "roll_deg": yaw * 0.15,
                    "angular_velocity_deg_s": 0.0}

        ps = [pose(0, 0.0), pose(1, 10.0)]
        ys = [yuv.rgb_to_yuv444(
            synth.render_view_ss(pano, cam, p, None, 0, ss=4, hud=False)).y for p in ps]
        warped = synth.psnr(synth.centre_crop(synth.ideal_warp(ys[0], ps[0], ps[1], cam)),
                            synth.centre_crop(ys[1]))
        unwarped = synth.psnr(synth.centre_crop(ys[0]), synth.centre_crop(ys[1]))
        assert warped - unwarped > 15.0, f"warp {warped:.2f} dB, no warp {unwarped:.2f} dB"
