// nxvc/vk/pipeline.hpp - compute pipelines from embedded SPIR-V.
//
// 3.2.6: "Same SPIR-V binary everywhere; specialization constants for subgroup
// size and 10-bit mode, no vendor #ifdefs in normative code."  So there is
// exactly one way to make a pipeline here: take a blob, bind a specialization
// map, optionally pin the subgroup size with VK_EXT_subgroup_size_control and
// REQUIRE_FULL_SUBGROUPS, and create.
#pragma once

#include <nxvc/vk/context.hpp>

#include <cstdint>
#include <initializer_list>
#include <span>
#include <string>
#include <unordered_map>
#include <vector>

namespace nxvc::vk {

// Reserved specialization constant ids.  Normative shaders use these and no
// others below 16; kernels may use 16+ freely.
enum : uint32_t {
    kSpecSubgroupSize = 0,   // the size the pipeline was created for
    kSpecTileSize = 1,       // 64 (3.2.3)
    kSpecClusterWidth = 2,   // 8 (3.2.6), never changes but explicit beats magic
    kSpecTenBit = 3,         // 0 = 8-bit, 1 = 10-bit
    kSpecWorkgroupSize = 4,  // local_size_x when the shader declares it as a spec id
};

// A typed specialization-constant map.  Everything is 4 bytes; that covers
// uint/int/float/bool as Vulkan lays them out for specialization.
class SpecConstants {
public:
    SpecConstants() = default;
    SpecConstants& set(uint32_t id, uint32_t v);
    SpecConstants& set(uint32_t id, int32_t v);
    SpecConstants& set(uint32_t id, float v);
    SpecConstants& set(uint32_t id, bool v);
    [[nodiscard]] bool empty() const noexcept { return entries_.empty(); }
    // Valid until the next mutation of this object.
    [[nodiscard]] VkSpecializationInfo info() const noexcept;

private:
    SpecConstants& put(uint32_t id, uint32_t raw);
    std::vector<VkSpecializationMapEntry> entries_;
    std::vector<uint32_t> data_;
};

// A SPIR-V module.  `code` is 4-byte aligned words; the embedded-shader
// headers generated by cmake/NxvcEmbedShaders.cmake produce exactly that.
class ShaderModule {
public:
    ShaderModule() = default;
    ShaderModule(const Context& ctx, std::span<const uint32_t> code,
                 std::string debug_name = {});
    ~ShaderModule();
    ShaderModule(ShaderModule&&) noexcept;
    ShaderModule& operator=(ShaderModule&&) noexcept;
    ShaderModule(const ShaderModule&) = delete;
    ShaderModule& operator=(const ShaderModule&) = delete;
    [[nodiscard]] VkShaderModule handle() const noexcept { return module_; }

private:
    void destroy() noexcept;
    const Context* ctx_ = nullptr;
    VkShaderModule module_ = VK_NULL_HANDLE;
};

// Descriptor set layout builder.  The codec uses one set, all bindings
// COMPUTE-stage, so this is deliberately thin.
class DescriptorSetLayout {
public:
    DescriptorSetLayout() = default;
    DescriptorSetLayout(const Context& ctx,
                        std::span<const VkDescriptorSetLayoutBinding> bindings,
                        VkDescriptorSetLayoutCreateFlags flags = 0);
    ~DescriptorSetLayout();
    DescriptorSetLayout(DescriptorSetLayout&&) noexcept;
    DescriptorSetLayout& operator=(DescriptorSetLayout&&) noexcept;
    DescriptorSetLayout(const DescriptorSetLayout&) = delete;
    DescriptorSetLayout& operator=(const DescriptorSetLayout&) = delete;
    [[nodiscard]] VkDescriptorSetLayout handle() const noexcept { return layout_; }

    // b(binding, type, count = 1) with COMPUTE stage, for terse call sites.
    static VkDescriptorSetLayoutBinding b(uint32_t binding, VkDescriptorType type,
                                          uint32_t count = 1,
                                          const VkSampler* immutable = nullptr) {
        return VkDescriptorSetLayoutBinding{binding, type, count,
                                            VK_SHADER_STAGE_COMPUTE_BIT, immutable};
    }

private:
    void destroy() noexcept;
    const Context* ctx_ = nullptr;
    VkDescriptorSetLayout layout_ = VK_NULL_HANDLE;
};

struct ComputePipelineDesc {
    std::span<const uint32_t> spirv;
    const char* entry_point = "main";
    std::span<const VkDescriptorSetLayout> set_layouts;
    uint32_t push_constant_size = 0;
    SpecConstants spec;
    // Pin the subgroup size with VK_EXT_subgroup_size_control.  0 means "leave
    // it to the driver"; the builder fills this from the probe when the caller
    // leaves it at kAuto.
    static constexpr uint32_t kAuto = UINT32_MAX;
    uint32_t required_subgroup_size = kAuto;
    bool require_full_subgroups = true;
    // When true (the default) the builder also injects kSpecSubgroupSize,
    // kSpecClusterWidth and kSpecTileSize unless the caller already set them.
    bool inject_standard_spec = true;
    uint32_t tile_size = 64;
    bool ten_bit = false;
    std::string debug_name;
};

class ComputePipeline {
public:
    ComputePipeline() = default;
    ComputePipeline(const Context& ctx, const ComputePipelineDesc& desc,
                    VkPipelineCache cache = VK_NULL_HANDLE);
    ~ComputePipeline();
    ComputePipeline(ComputePipeline&&) noexcept;
    ComputePipeline& operator=(ComputePipeline&&) noexcept;
    ComputePipeline(const ComputePipeline&) = delete;
    ComputePipeline& operator=(const ComputePipeline&) = delete;

    [[nodiscard]] VkPipeline handle() const noexcept { return pipeline_; }
    [[nodiscard]] VkPipelineLayout layout() const noexcept { return layout_; }
    // The subgroup size this pipeline actually runs at: the pinned size where
    // one was pinned, else the device's reported size.  Shaders receive the
    // same number through kSpecSubgroupSize.
    [[nodiscard]] uint32_t subgroupSize() const noexcept { return subgroup_size_; }

    void bind(VkCommandBuffer cmd) const;
    void push(VkCommandBuffer cmd, const void* data, uint32_t size,
              uint32_t offset = 0) const;
    template <class T>
    void push(VkCommandBuffer cmd, const T& v) const {
        push(cmd, &v, static_cast<uint32_t>(sizeof(T)));
    }

private:
    void destroy() noexcept;
    const Context* ctx_ = nullptr;
    VkPipeline pipeline_ = VK_NULL_HANDLE;
    VkPipelineLayout layout_ = VK_NULL_HANDLE;
    uint32_t subgroup_size_ = 0;
};

// A trivial persistent pipeline cache backed by a file.  Adreno's compiler is
// slow enough that skipping it on a warm start is worth the 30 lines.
class PipelineCache {
public:
    PipelineCache() = default;
    PipelineCache(const Context& ctx, const std::string& path);
    ~PipelineCache();
    PipelineCache(PipelineCache&&) noexcept;
    PipelineCache& operator=(PipelineCache&&) noexcept;
    PipelineCache(const PipelineCache&) = delete;
    PipelineCache& operator=(const PipelineCache&) = delete;
    [[nodiscard]] VkPipelineCache handle() const noexcept { return cache_; }
    void save() const;

private:
    void destroy() noexcept;
    const Context* ctx_ = nullptr;
    VkPipelineCache cache_ = VK_NULL_HANDLE;
    std::string path_;
};

// A single descriptor pool + set, sized from the layout's bindings.  Enough
// for the codec, which binds one set per pass and never updates per frame.
class DescriptorSet {
public:
    DescriptorSet() = default;
    DescriptorSet(const Context& ctx, VkDescriptorSetLayout layout,
                  std::span<const VkDescriptorPoolSize> sizes);
    ~DescriptorSet();
    DescriptorSet(DescriptorSet&&) noexcept;
    DescriptorSet& operator=(DescriptorSet&&) noexcept;
    DescriptorSet(const DescriptorSet&) = delete;
    DescriptorSet& operator=(const DescriptorSet&) = delete;

    [[nodiscard]] VkDescriptorSet handle() const noexcept { return set_; }
    DescriptorSet& write(uint32_t binding, VkDescriptorType type,
                         const VkDescriptorBufferInfo& info);
    DescriptorSet& write(uint32_t binding, VkDescriptorType type,
                         const VkDescriptorImageInfo& info);
    void flush();  // vkUpdateDescriptorSets for everything queued

private:
    void destroy() noexcept;
    const Context* ctx_ = nullptr;
    VkDescriptorPool pool_ = VK_NULL_HANDLE;
    VkDescriptorSet set_ = VK_NULL_HANDLE;
    std::vector<VkWriteDescriptorSet> writes_;
    std::vector<VkDescriptorBufferInfo> buffer_infos_;
    std::vector<VkDescriptorImageInfo> image_infos_;
};

}  // namespace nxvc::vk
