// Placeholder decoder: Pass A is a no-op, Pass B paints tiles by state.
//
// See nxc_decoder.h for the contract and for what replaces this file. The point
// of shipping a placeholder rather than an empty screen is that everything
// *around* the decoder -- the receive thread, the depacketizer, the 4-slot ring,
// the per-tile metadata SSBO, the deadline state machine, the feedback packets
// and the presentation path -- is exercised and measurable today, so that when
// vk/ lands the only new variable is the decoder itself.
//
// It owns its own descriptor set layout, pool, set and pipeline, exactly as the
// real decoder will: the client hands it buffer and image handles through
// DecodeSubmit and never reaches inside.
#include "nxc_decoder.h"

#include <cstring>
#include <vector>

#include "tiles.spv.h"   // generated by cmake/gen_spv.cmake

namespace nxc {
namespace {

struct TilesPush {
    uint32_t img_w, img_h;
    uint32_t grid_w, grid_h;
    uint32_t band_rows;
    uint32_t frame_id;
};

class PlaceholderDecoder final : public Decoder {
public:
    ~PlaceholderDecoder() override { destroy(); }

    const char* name() const override { return "placeholder (paint-by-state)"; }
    bool is_placeholder() const override { return true; }

    bool create(const DecoderCreateInfo& ci) override {
        dev_ = ci.device;
        stream_ = ci.stream;

        // PAPER 3.2.6: refuse subgroups smaller than 8. The placeholder does no
        // cross-lane work so it does not actually care, but the check belongs at
        // the seam so the failure shows up here rather than inside the real
        // decoder later.
        if (ci.subgroup_size != 0 && ci.subgroup_size < kMinSubgroupSize) {
            log_err("decoder: subgroup size %u < %u; PAPER 3.2.6 puts this device "
                    "on the hybrid path (PAPER 3.5), not pure compute",
                    ci.subgroup_size, kMinSubgroupSize);
            return false;
        }

        // 0 = luma storage image, 1 = chroma storage image, 2 = tile metadata.
        VkDescriptorSetLayoutBinding b[3] = {};
        for (uint32_t i = 0; i < 3; ++i) {
            b[i].binding = i;
            b[i].descriptorCount = 1;
            b[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
            b[i].descriptorType = (i < 2) ? VK_DESCRIPTOR_TYPE_STORAGE_IMAGE
                                          : VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        }

        VkDescriptorSetLayoutCreateInfo lci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
        lci.bindingCount = 3;
        lci.pBindings = b;
        if (vkCreateDescriptorSetLayout(dev_, &lci, nullptr, &set_layout_) != VK_SUCCESS)
            return false;

        VkDescriptorPoolSize ps[2] = {
            {VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 2},
            {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1},
        };
        VkDescriptorPoolCreateInfo pci{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
        pci.maxSets = 1;
        pci.poolSizeCount = 2;
        pci.pPoolSizes = ps;
        if (vkCreateDescriptorPool(dev_, &pci, nullptr, &pool_) != VK_SUCCESS) return false;

        VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
        ai.descriptorPool = pool_;
        ai.descriptorSetCount = 1;
        ai.pSetLayouts = &set_layout_;
        if (vkAllocateDescriptorSets(dev_, &ai, &set_) != VK_SUCCESS) return false;

        VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(TilesPush)};
        VkPipelineLayoutCreateInfo plci{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
        plci.setLayoutCount = 1;
        plci.pSetLayouts = &set_layout_;
        plci.pushConstantRangeCount = 1;
        plci.pPushConstantRanges = &pcr;
        if (vkCreatePipelineLayout(dev_, &plci, nullptr, &pipe_layout_) != VK_SUCCESS)
            return false;

        VkShaderModuleCreateInfo smci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
        smci.codeSize = sizeof(tiles_spv);
        smci.pCode = tiles_spv;
        VkShaderModule sm = VK_NULL_HANDLE;
        if (vkCreateShaderModule(dev_, &smci, nullptr, &sm) != VK_SUCCESS) return false;

        VkComputePipelineCreateInfo cpci{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
        cpci.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        cpci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        cpci.stage.module = sm;
        cpci.stage.pName = "main";
        cpci.layout = pipe_layout_;
        VkResult r = vkCreateComputePipelines(dev_, VK_NULL_HANDLE, 1, &cpci, nullptr, &pipe_);
        vkDestroyShaderModule(dev_, sm, nullptr);
        if (r != VK_SUCCESS) return false;

        log_info("decoder: %s ready", name());
        return true;
    }

    void destroy() override {
        if (!dev_) return;
        if (pipe_)        vkDestroyPipeline(dev_, pipe_, nullptr);
        if (pipe_layout_) vkDestroyPipelineLayout(dev_, pipe_layout_, nullptr);
        if (pool_)        vkDestroyDescriptorPool(dev_, pool_, nullptr);
        if (set_layout_)  vkDestroyDescriptorSetLayout(dev_, set_layout_, nullptr);
        pipe_ = VK_NULL_HANDLE; pipe_layout_ = VK_NULL_HANDLE;
        pool_ = VK_NULL_HANDLE; set_layout_ = VK_NULL_HANDLE;
        dev_ = VK_NULL_HANDLE;
    }

    // PAPER 3.2.2. Nothing to do: there is no bitstream to entropy decode yet.
    // The real implementation dispatches one workgroup of kPassAWorkgroup per
    // tile, eight interleaved rANS lanes sharing a read pointer (PAPER 6.3), and
    // ends with a buffer barrier onto the coefficient SSBO that Pass B reads.
    void record_pass_a(VkCommandBuffer, const DecodeSubmit&) override {}

    void record_pass_b(VkCommandBuffer cb, const DecodeSubmit& s) override {
        if (!pipe_ || s.output_luma == VK_NULL_HANDLE ||
            s.output_chroma == VK_NULL_HANDLE || s.tile_meta == VK_NULL_HANDLE) {
            return;
        }

        // Re-point the descriptors only when a handle actually changed: the
        // plane views change on every swapchain rebuild, the metadata buffer
        // never does.
        if (s.output_luma != bound_luma_ || s.output_chroma != bound_chroma_ ||
            s.tile_meta != bound_meta_) {
            VkDescriptorImageInfo li{};
            li.imageView = s.output_luma;
            li.imageLayout = VK_IMAGE_LAYOUT_GENERAL;
            VkDescriptorImageInfo cih{};
            cih.imageView = s.output_chroma;
            cih.imageLayout = VK_IMAGE_LAYOUT_GENERAL;
            VkDescriptorBufferInfo bi{s.tile_meta, 0, VK_WHOLE_SIZE};

            VkWriteDescriptorSet w[3] = {};
            for (uint32_t i = 0; i < 3; ++i) {
                w[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
                w[i].dstSet = set_;
                w[i].dstBinding = i;
                w[i].descriptorCount = 1;
            }
            w[0].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE; w[0].pImageInfo = &li;
            w[1].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE; w[1].pImageInfo = &cih;
            w[2].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER; w[2].pBufferInfo = &bi;
            vkUpdateDescriptorSets(dev_, 3, w, 0, nullptr);
            bound_luma_ = s.output_luma;
            bound_chroma_ = s.output_chroma;
            bound_meta_ = s.tile_meta;
        }

        TilesPush pc{};
        pc.img_w = s.output_width;
        pc.img_h = s.output_height;
        pc.grid_w = stream_.cols;
        pc.grid_h = stream_.rows;
        pc.band_rows = stream_.band_rows;
        pc.frame_id = s.frame_id;

        vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_COMPUTE, pipe_);
        vkCmdBindDescriptorSets(cb, VK_PIPELINE_BIND_POINT_COMPUTE, pipe_layout_, 0, 1,
                                &set_, 0, nullptr);
        vkCmdPushConstants(cb, pipe_layout_, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);
        vkCmdDispatch(cb, (s.output_width + 15) / 16, (s.output_height + 15) / 16, 1);
    }

private:
    VkDevice     dev_ = VK_NULL_HANDLE;
    StreamConfig stream_;
    VkDescriptorSetLayout set_layout_ = VK_NULL_HANDLE;
    VkDescriptorPool      pool_ = VK_NULL_HANDLE;
    VkDescriptorSet       set_ = VK_NULL_HANDLE;
    VkPipelineLayout      pipe_layout_ = VK_NULL_HANDLE;
    VkPipeline            pipe_ = VK_NULL_HANDLE;
    VkImageView           bound_luma_ = VK_NULL_HANDLE;
    VkImageView           bound_chroma_ = VK_NULL_HANDLE;
    VkBuffer              bound_meta_ = VK_NULL_HANDLE;
};

}  // namespace

std::unique_ptr<Decoder> create_placeholder_decoder() {
    return std::make_unique<PlaceholderDecoder>();
}

}  // namespace nxc
