cmake_minimum_required(VERSION 3.20)
project(astc_safety LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
find_package(Vulkan REQUIRED)
find_library(LZ4_LIB lz4 REQUIRED)
find_library(ZSTD_LIB zstd REQUIRED)
add_executable(astc-safety src/main.cpp)
target_link_libraries(astc-safety PRIVATE Vulkan::Vulkan "${ZSTD_LIB}" "${LZ4_LIB}")
target_compile_options(astc-safety PRIVATE -O3 -Wall -Wextra -Wpedantic)
