#!/usr/bin/env python3
"""Generate nxe_neglog2.inc -- the Q10 bit cost of a 10-bit rANS probability.

The rate model needs -log2(freq/kProbTotal) and must produce the SAME number on
a host libm, on a GPU, and on lavapipe.  `log2` does not have that property, so
the function is a table: 1025 entries, computed once here, checked in, and read
by both the C model and the shader.

Regenerate with:  python3 scripts/gen-neglog2.py > vk/encoder/forward/nxe_neglog2.inc
"""
import math

TOTAL = 1024        # kProbTotal, NXVC_PROB_BITS = 10
SHIFT = 10          # Q10


def main():
    v = [0] * (TOTAL + 1)
    for f in range(1, TOTAL + 1):
        v[f] = int(round(-math.log2(f / float(TOTAL)) * (1 << SHIFT)))
    print("/* Generated by scripts/gen-neglog2.py -- do not edit. */")
    print("/* nxe_neglog2_q10[f] = round(-log2(f/1024) * 1024), f in 1..1024. */")
    print("/* f == 0 never occurs: every context row is >= 1 per entry. */")
    for i in range(0, TOTAL + 1, 8):
        row = ", ".join("%5d" % x for x in v[i:i + 8])
        print("    %s," % row)


main()
