"""Tables for a ``spatial`` run, rendered into hybrid/RESULTS-SPATIAL.md.

Kept apart from :mod:`nxvchybrid.report` because the two experiments answer
different questions and share no columns: the layered sweep reports PSNR-Y
against a modelled codec, this one reports eccentricity-weighted PSNR and
FovVideoVDP JOD against the real one.
"""

from __future__ import annotations

import os

from . import spatial as sp


def _fmt(v, nd=2, dash="--"):
    return dash if v is None else f"{v:.{nd}f}"


def _short_codec_dir(p: str) -> str:
    """The codec path, relative to the checkout, so the file is portable."""
    parts = p.replace(os.sep, "/").split("/")
    for anchor in ("build-ref", "build-dev", "build-release"):
        if anchor in parts:
            return "/".join(parts[parts.index(anchor):])
    return os.path.basename(p.rstrip("/")) or p


def _by_kind(results, kind):
    return [r for r in results if r.get("kind") == kind and "error" not in r]


#: A point whose measured rate falls this far below its target did not spend
#: its budget: the inset saturated at QP 0 and the leftover bits went nowhere.
#: They are marked rather than rebalanced, because a real rate controller would
#: have given them back to the periphery and this simulator does not.
UNDERSPENT = 0.97


def _grid(results, total, insets, fracs, key):
    out = {}
    for r in _by_kind(results, "spatial"):
        if abs(r["total_mbit"] - total) > 1e-6 or r.get("tag"):
            continue
        out[(r["inset"], round(r["base_frac"], 3))] = (r.get(key), _under(r))
    return out


def _under(r) -> bool:
    t = r.get("total_mbit") or 0.0
    return bool(t) and (r.get("measured_mbit", 0.0) < UNDERSPENT * t)


def _cell(v, under=False, nd=2):
    return _fmt(v, nd) + (" +" if under and v is not None else "")


def geometry_table(seq_eye_px: int, hfov: float, insets) -> str:
    """What each simulator inset is, in angle and in headset pixels."""
    L = ["## What the inset sizes mean\n",
         "The simulator's eye is "
         f"{seq_eye_px} px over {hfov:g} degrees; the Pico 4's is 2160 px over 81.2",
         "(`docs/RATECONTROL.md` 6.3, `ppd_center = 22.0`). The translation between",
         "them is **angular**, not a pixel scale. `decode` is the cost model of the",
         "last section, luma-only at the 441.6 MHz the bench measured.\n",
         "| sim inset | half-angle | Pico 4 inset | tiles/eye | decode | +chroma |",
         "|---|---|---|---|---|---|"]
    for i in insets:
        d = sp.device_inset_px(i, seq_eye_px, hfov)
        n = sp.tiles_for(d)
        L.append(f"| {i} px | +/-{sp.half_angle_of_inset(i, seq_eye_px, hfov):.2f} deg | "
                 f"{d} px | {n // 2} | {sp.decode_ms(n):.2f} ms | "
                 f"{sp.decode_ms(n, chroma=True):.2f} ms |")
    w, h = sp.eye_box_inset(3.0)
    L.append("")
    L.append(f"For reference, the inset the Pico 4's fixed foveation asks for -- the")
    L.append(f"{sp.EYE_BOX_H_DEG:g} x {sp.EYE_BOX_V_DEG:g} degree eye box of PAPER 5.1.3 plus the")
    L.append(f"{sp.FOVEA_DEG:g} degree fovea and a 3 degree pad -- is **{w} x {h} px**, "
             f"{(w // 64) * (h // 64)} tiles per eye,")
    L.append(f"**{sp.decode_ms(2 * (w // 64) * (h // 64)):.2f} ms** luma-only and "
             f"{sp.decode_ms(2 * (w // 64) * (h // 64), chroma=True):.2f} ms with chroma.")
    L.append("")
    return "\n".join(L)


def render(d: dict) -> str:
    res = [r for r in d["results"]]
    ok = [r for r in res if "error" not in r]
    bad = [r for r in res if "error" in r]
    spatials = _by_kind(res, "spatial")
    grid = [r for r in spatials if not r.get("tag")]
    extras = [r for r in spatials if r.get("tag")]
    totals = sorted({r["total_mbit"] for r in ok})
    insets = sorted({r["inset"] for r in grid})
    fracs = sorted({round(r["base_frac"], 3) for r in grid})
    have_jod = any(r.get("jod") is not None for r in ok)
    hfov = d.get("hfov", 95.0)
    eye_px = (ok[0]["size"][0] // 2) if ok else 1024

    L: list[str] = []
    A = L.append
    A("# The spatial hybrid: results\n")
    A("A hardware HEVC **periphery** plus an NX Warp **fovea inset**, composited")
    A("with a feathered boundary. Generated by `nxvc-hybridsim spatial`; the")
    A("design is in [../docs/SPATIAL-HYBRID.md](../docs/SPATIAL-HYBRID.md) and the")
    A("arrangement it is *not* is [ADR 0022](../docs/adr/0022-hybrid-mode-is-not-a-quality-tool.md).\n")
    A(f"Sequence: `{os.path.basename(d.get('seq', '?'))}`"
      + (f", {ok[0]['frames']} frames at {ok[0]['size'][0]}x{ok[0]['size'][1]} "
         f"{ok[0]['pix_fmt']} side-by-side" if ok else "")
      + f", {d.get('hfov', 95)} degree eye. ")
    A("Bitrates are quoted throughout as their **2 x 2048^2 x 90 Hz equivalent**.")
    A("The inset is coded by the real codec (`nxv-enc`/`nxv-dec`, intra + inter,")
    A(f"`{_short_codec_dir(d.get('codec_dir', '?'))}`); the periphery is x265 under the")
    A("zerolatency P-only settings of `nxvchybrid.base`, at full resolution")
    A("(ADR 0022 item 3).\n")
    if d.get("metrics", {}).get("fvvdp"):
        A(f"FovVideoVDP: {d['metrics']['fvvdp']}.\n")
    A(f"Feather: {d.get('feather')} px. Run time {d.get('seconds', 0) / 60:.0f} min.\n")
    if bad:
        A(f"**{len(bad)} point(s) failed**: "
          + ", ".join(f"`{r['label']}`" for r in bad) + "\n")

    # --- anchors ---------------------------------------------------------
    A("---\n")
    A("## Anchors\n")
    A("`x265` is the flat P-only encode of the whole frame at the full budget --")
    A("what WiVRn streams today. `x265-fov` is `x265-p-refresh`: periodic intra")
    A("refresh instead of IDRs plus the concentric delta-QP map of")
    A("`tools/quality/nxq/qpmap.py`, bisected on CRF to the same budget. It is the")
    A("foveated hardware-class opponent, and it is the one that matters.\n")
    A("| Mbit | anchor | measured | fov-PSNR | fovea | periphery | fov-SSIM"
      + (" | JOD |" if have_jod else " |"))
    A("|---|---|---|---|---|---|---|" + ("---|" if have_jod else ""))
    for t in totals:
        for kind, name in (("hevc", "x265"), ("hevc-fov", "x265-fov")):
            for r in _by_kind(res, kind):
                if abs(r["total_mbit"] - t) > 1e-6:
                    continue
                A(f"| {t:g} | {name} | {r['measured_mbit']:.1f} | "
                  f"{_fmt(r.get('fov_psnr_y'))} | {_fmt(r.get('psnr_fovea'))} | "
                  f"{_fmt(r.get('psnr_periphery'))} | {_fmt(r.get('fov_ssim_y'), 4)}"
                  + (f" | {_fmt(r.get('jod'), 3)} |" if have_jod else " |"))
    A("")

    # --- the grid --------------------------------------------------------
    A("---\n")
    A("## The grid\n")
    A("Rows are the inset side in pixels per eye of the *simulator*, with the")
    A("Pico 4 inset that subtends the same angle after the arrow (see \"What the")
    A("inset sizes mean\" below); columns are")
    A("the **periphery share** of the total bitrate. The cell is")
    A("eccentricity-weighted PSNR-Y at a centre fixation, which is where a")
    A("fixed-foveation headset puts the inset and where the foveated anchor puts")
    A("its low-QP box. A **+** marks a point that could not spend its budget:")
    A("the inset saturated at QP 0 and the leftover bits went nowhere.\n")
    for t in totals:
        g = _grid(res, t, insets, fracs, "fov_psnr_y")
        if not g:
            continue
        anch = {k: next((r.get("fov_psnr_y") for r in _by_kind(res, k)
                         if abs(r["total_mbit"] - t) < 1e-6), None)
                for k in ("hevc", "hevc-fov")}
        A(f"### {t:g} Mbit\n")
        A("| inset -> Pico 4 | " + " | ".join(f"periphery {f:.0%}" for f in fracs)
          + " | best | vs x265 | vs x265-fov |")
        A("|---" * (len(fracs) + 4) + "|")
        for i in insets:
            row = [g.get((i, f), (None, False)) for f in fracs]
            vals = [v for v, _ in row if v is not None]
            best = max(vals) if vals else None
            cells = " | ".join(_cell(v, u) for v, u in row)
            dev = sp.device_inset_px(i, eye_px, hfov)
            if best is None:
                A(f"| {i} -> {dev} | {cells} | -- | -- | -- |")
                continue
            bf = fracs[[v for v, _ in row].index(best)]
            d1 = f"{best - anch['hevc']:+.2f}" if anch["hevc"] else "--"
            d2 = f"{best - anch['hevc-fov']:+.2f}" if anch["hevc-fov"] else "--"
            A(f"| {i} -> {dev} | {cells} | "
              f"**{best:.2f}** @ {bf:.0%} | {d1} | {d2} |")
        A("")

    if have_jod:
        A("### FovVideoVDP, JOD\n")
        A("Higher is better; 1 JOD is a 75 percent preference in a pairwise")
        A("comparison. The anchors are the last two columns.\n")
        for t in totals:
            g = _grid(res, t, insets, fracs, "jod")
            if not g:
                continue
            A(f"**{t:g} Mbit**\n")
            A("| inset | " + " | ".join(f"{f:.0%}" for f in fracs)
              + " | best | x265 | x265-fov |")
            A("|---" * (len(fracs) + 4) + "|")
            av = {k: next((r.get("jod") for r in _by_kind(res, k)
                           if abs(r["total_mbit"] - t) < 1e-6), None)
                  for k in ("hevc", "hevc-fov")}
            for i in insets:
                row = [g.get((i, f), (None, False)) for f in fracs]
                vals = [v for v, _ in row if v is not None]
                A(f"| {i} | " + " | ".join(_cell(v, u, 3) for v, u in row)
                  + f" | **{_fmt(max(vals) if vals else None, 3)}** | "
                  + f"{_fmt(av['hevc'], 3)} | {_fmt(av['hevc-fov'], 3)} |")
            A("")

    # --- the winner per budget ------------------------------------------
    A("---\n")
    A("## Best configuration per budget\n")
    A("| Mbit | inset | split | inset Mbit | inset QP | fov-PSNR | fovea | periphery"
      + (" | JOD" if have_jod else "") + " | vs x265 | vs x265-fov |")
    A("|---|---|---|---|---|---|---|---|---|---|" + ("---|" if have_jod else ""))
    for t in totals:
        cand = [r for r in grid if abs(r["total_mbit"] - t) < 1e-6
                and r.get("fov_psnr_y") is not None]
        if not cand:
            continue
        b = max(cand, key=lambda r: r["fov_psnr_y"])
        a1 = next((r for r in _by_kind(res, "hevc") if abs(r["total_mbit"] - t) < 1e-6), None)
        a2 = next((r for r in _by_kind(res, "hevc-fov") if abs(r["total_mbit"] - t) < 1e-6), None)
        A(f"| {t:g} | {b['inset']} | {b['base_frac']:.0%}/{1 - b['base_frac']:.0%} | "
          f"{b['inset_mbit']:.1f} | {b.get('inset_qp', '-')} | "
          f"**{_fmt(b['fov_psnr_y'])}** | {_fmt(b['psnr_fovea'])} | "
          f"{_fmt(b['psnr_periphery'])}"
          + (f" | {_fmt(b.get('jod'), 3)}" if have_jod else "")
          + f" | {_fmt(b['fov_psnr_y'] - a1['fov_psnr_y']) if a1 else '--'}"
          + f" | {_fmt(b['fov_psnr_y'] - a2['fov_psnr_y']) if a2 else '--'} |")
    A("")

    # --- what the arrangement actually buys ------------------------------
    A("---\n")
    A("## Where the bits went: the fovea/periphery trade\n")
    A("The weighted column above pools the whole view, and the periphery is most")
    A("of it even after the acuity weighting, so a fovea win can be invisible")
    A("there. This table pulls the two regions apart. `best fovea` is the grid")
    A("point with the highest PSNR *inside the 8 degree fovea disc* -- what the")
    A("arrangement is for -- and its periphery column is what that cost.\n")
    A("| Mbit | arm | config | fovea | periphery | gap | fov-PSNR"
      + (" | JOD |" if have_jod else " |"))
    A("|---|---|---|---|---|---|---|" + ("---|" if have_jod else ""))
    for t in totals:
        rows = []
        for kind, name in (("hevc", "x265"), ("hevc-fov", "x265-fov")):
            r = next((x for x in _by_kind(res, kind)
                      if abs(x["total_mbit"] - t) < 1e-6), None)
            if r:
                rows.append((name, "--", r))
        cand = [r for r in grid if abs(r["total_mbit"] - t) < 1e-6
                and r.get("psnr_fovea") is not None]
        if cand:
            b = max(cand, key=lambda r: r["psnr_fovea"])
            rows.append(("spatial, best fovea",
                         f"inset {b['inset']}, {b['base_frac']:.0%} periphery", b))
            w = max(cand, key=lambda r: r["fov_psnr_y"])
            if w is not b:
                rows.append(("spatial, best weighted",
                             f"inset {w['inset']}, {w['base_frac']:.0%} periphery", w))
        for name, cfg, r in rows:
            gap = r["psnr_fovea"] - r["psnr_periphery"]
            A(f"| {t:g} | {name} | {cfg} | {_fmt(r.get('psnr_fovea'))} | "
              f"{_fmt(r.get('psnr_periphery'))} | {gap:+.2f} | "
              f"{_fmt(r.get('fov_psnr_y'))}"
              + (f" | {_fmt(r.get('jod'), 3)} |" if have_jod else " |"))
    A("")
    A("`gap` is the fovea-minus-periphery difference: it is the direct measure of")
    A("how hard an arm is foveating. A flat encode shows a few tenths of a dB; an")
    A("arm that is really concentrating bits on the fovea shows several.\n")

    # --- off-grid points -------------------------------------------------
    if extras:
        A("---\n")
        A("## A/B points\n")
        A("| point | Mbit | inset | split | feather | inset hole | fov-PSNR | "
          "fovea | periphery" + (" | JOD |" if have_jod else " |"))
        A("|---|---|---|---|---|---|---|---|---|" + ("---|" if have_jod else ""))
        for r in extras:
            A(f"| {r.get('tag')} | {r['total_mbit']:g} | {r['inset']} | "
              f"{r['base_frac']:.0%} | {r['feather']} | +{r['hole_dq']} QP | "
              f"{_fmt(r.get('fov_psnr_y'))} | {_fmt(r.get('psnr_fovea'))} | "
              f"{_fmt(r.get('psnr_periphery'))}"
              + (f" | {_fmt(r.get('jod'), 3)} |" if have_jod else " |"))
        A("")

    # --- geometry and the decoder cost model ----------------------------
    A("---\n")
    if ok:
        A(geometry_table(eye_px, hfov, insets))
    A("---\n")
    A(decoder_table())
    return "\n".join(L) + "\n"


def decoder_table() -> str:
    """The Pico 4 tile-cost model, from bench/README.md.

    Kept next to the quality tables because the two together are the whole
    argument: the inset size the quality sweep wants and the inset size the
    decoder can afford are the same number, and it has to be both.
    """
    L = ["## Decoder cost on the Pico 4\n",
         "K5 (Pass A + Pass B, PAPER 3.4) measured **28.0 ms p50** for the 2048",
         "tiles of a 2 x 2048^2 frame on the Pico 4 with the GPU pinned at",
         "441.6 MHz (`bench/README.md`; the run-to-run spread was 28.0 to 33.3 ms",
         "and 28.0 is used, which is the optimistic end). **Assumption: the cost is",
         "linear in the tile count** -- K5 is per-tile work with no frame-level",
         "stage, and every kernel dispatches one workgroup cluster per tile -- so",
         "the per-tile cost is 13.67 us at 441.6 MHz and 10.28 us at the part's",
         "587 MHz. `+chroma` adds the 50 percent the bench's luma-only transform",
         "omits (`bench/README.md`, \"One transform plane, no chroma\").\n",
         "| inset per eye | tiles/eye | tiles | 441.6 MHz | +chroma | 587 MHz | +chroma |",
         "|---|---|---|---|---|---|---|"]
    for px in (512, 640, 768, 832, 896, 1024, 1152, 1280, 1344, 2048):
        n = sp.tiles_for(px)
        L.append(f"| {px} | {n // 2} | {n} | {sp.decode_ms(n):.2f} ms | "
                 f"{sp.decode_ms(n, chroma=True):.2f} ms | "
                 f"{sp.decode_ms(n, clock_mhz=sp.PART_CLOCK_MHZ):.2f} ms | "
                 f"{sp.decode_ms(n, clock_mhz=sp.PART_CLOCK_MHZ, chroma=True):.2f} ms |")
    L.append("")
    L.append("Largest tile-aligned inset that fits a budget, both eyes:\n")
    L.append("| budget | 441.6 MHz | +chroma | 587 MHz | +chroma |")
    L.append("|---|---|---|---|---|")
    for ms in (2.0, 5.0, 7.0, 10.0, 12.0):
        L.append(
            f"| {ms:g} ms | {sp.inset_fitting(ms)} px | "
            f"{sp.inset_fitting(ms, chroma=True)} px | "
            f"{sp.inset_fitting(ms, clock_mhz=sp.PART_CLOCK_MHZ)} px | "
            f"{sp.inset_fitting(ms, clock_mhz=sp.PART_CLOCK_MHZ, chroma=True)} px |")
    L.append("")
    return "\n".join(L)
